### ISSUE TITLE
FE: Resource search bar

### ISSUE THREAD

**Issue by dareek** [disconnect3d/sensors-monitor#22]
**To do:**
	There is a search bar. When user types something, only resources containing this text should be displayed. 
	When clicking on select all / deselect all, only visible measurements should be affected. 

**How to - search:**
Method 1)
	Again, use angular. But only if you did printing (issue Dynamically adding resources) with Angular too. Then it’s straightforward. See examples in google (angular filter search).
Method 2)
	Well, jQuery. Select all $(“.measItem”), iterate though them (jQuery has filter method), check if $(“.measItemName”) or $(“.measResName”) or (“.measResValue”) contain user’s text and if not then addClass(“template”) to those .measItems that are to be hidden. 

**How to – select all:**
	Just modify selector in existing method to select only the elements that don’t have “template” class (method 2 above) or has css(“display”) != “none”.

**Comment by Kamill0** [comment]
Done for item and resource names.
